domains                  = "ausente-xc.kushikimi.xyz"
name                     = "e-ausente"
namespace                = "e-ausente"
origin_pool_service_name = "boutique-frontend.ausente"
origin_pool_virtual_site = "ausente-vsite"
